services:
  apigateway:
    image: apigateway
    container_name: apigateway
    build:
      context: .
      dockerfile: ./src/Gateway/ApiGateway/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - motorcycleservice
      - rentservice
      - deliverymanservice
    restart: always

  motorcycleservice:
    image: motorcycleservice
    container_name: motorcycleservice
    build:
      context: .
      dockerfile: ./src/Services/MotorcycleService/Dockerfile
    restart: always

  rentservice:
    image: rentservice
    container_name: rentservice
    build:
      context: .
      dockerfile: ./src/Services/RentService/Dockerfile
    restart: always

  deliverymanservice:
    image: deliverymanservice
    container_name: deliverymanservice
    build:
      context: .
      dockerfile: ./src/Services/DeliveryManService/Dockerfile
    restart: always