services:
  api:
    image: lucasbenhur_api
    container_name: lucasbenhur_api
    build:
      context: .
      dockerfile: ./src/Api/Dockerfile
    ports:
      - "5000:80"
  worker:
    image: lucasbenhur_worker
    container_name: lucasbenhur_worker
    build:
      context: .
      dockerfile: ./src/Worker/Dockerfile
    ports:
      - "5001:80"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: lucasbenhur-rabbitmq
    hostname: lucasbenhur-rabbitmq
    ports:
      - "8080:15672"
      - "5662:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: lucasbenhur