version: '3.8'

networks:
  motorcycle_maintenance:
    driver: bridge

services:
  apigateway:
    image: apigateway
    container_name: apigateway
    build:
      context: .
      dockerfile: ./src/Gateway/ApiGateway/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - motorcycleservice
      - rentservice
      - deliverymenservice
    restart: always
    networks:
      - motorcycle_maintenance

  motorcycleservice:
    image: motorcycleservice
    container_name: motorcycleservice
    build:
      context: .
      dockerfile: ./src/Services/MotorcycleService/Dockerfile
    restart: always
    networks:
      - motorcycle_maintenance

  rentservice:
    image: rentservice
    container_name: rentservice
    build:
      context: .
      dockerfile: ./src/Services/RentService/Dockerfile
    restart: always
    networks:
      - motorcycle_maintenance

  deliverymenservice:
    image: deliverymenservice
    container_name: deliverymenservice
    build:
      context: .
      dockerfile: ./src/Services/DeliveryMenService/Dockerfile
    restart: always
    networks:
      - motorcycle_maintenance
