services:
  api:
    image: lucasbenhur_motorcyclemaintenance_api
    container_name: lucasbenhur_motorcyclemaintenance_api
    build:
      context: .
      dockerfile: ./src/LucasBenHur.MotorcycleMaintenance.Api/Dockerfile
    ports:
      - "80:80"
    restart: always
  worker:
    image: lucasbenhur_motorcyclemaintenance_worker
    container_name: lucasbenhur_motorcyclemaintenance_worker
    build:
      context: .
      dockerfile: ./src/LucasBenHur.MotorcycleMaintenance.Worker/Dockerfile
    restart: always
  rabbitmq:
    image: rabbitmq:3-management
    container_name: lucasbenhur_motorcyclemaintenance_rabbitmq
    hostname: lucasbenhur_motorcyclemaintenance_rabbitmq
    ports:
      - "8080:15672"
      - "5662:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always